### ISSUE TITLE
Connection error from hasura backend plus on local k3d cluster

### ISSUE THREAD

**Issue by jkaliaSignify** [platyplus/platyplus#13]
Tried installing it on my  local k3d cluster using the given helm commands. only difference was `my-release` to something else

Hasura Backend Plus is giving these logs.

![image](https://user-images.githubusercontent.com/66690952/132958723-e8be8b9f-768b-435f-acaf-7e8182013b1d.png)

**Comment by plmercereau** [comment]
Hello @jkaliaSignify, the last version of Hasura-backend-plus introduced a breaking change - and I marked to use the `latest` version in the default chart values... 
I will fix that asap

**Comment by plmercereau** [comment]
Hello,
I just published a fix in a new chart version, could you try it out? Don't forget to remote the PVC of your previous test as postgres will need to run some init scripts

**Comment by jkaliaSignify** [comment]
Could not recreate error after update. closing issue. thanks!
