### ISSUE TITLE
Support for namespace ingress

### ISSUE THREAD

**Issue by preiddygarcia** [platyplus/platyplus#14]
Hi, why not add support for add in metadata the namespace?

**Comment by plmercereau** [comment]
Do you mean the same namespace as for the release, or a different namespace for the Ingress resource?

I think when not given, the namespace that will be used corresponds to the one given by the `--namespace` arg - falling back to the current active namespace.
So `metadata.namespace` is kind of implicit (see [google cloud best practices on namespaces](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-organizing-with-namespaces))

**Comment by preiddygarcia** [comment]
Ok, thanks 👍
