### ISSUE TITLE
Cannot specify jwk_url instead of key+type in Hasura helm chart

### ISSUE THREAD

**Issue by mstephano** [platyplus/platyplus#16]
I am currently using Hasura and Keycloak in Kubernetes, and in order to connect both, I need the following in my values.yaml:
```
jwtSecret: '{"jwk_url": "http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs"}'
```

However, the template `hasura-secrets.yaml` file needs a `key`, but if we provide a key (empty of filled) with jwk_url, **Hasura will not work**. For example:
```jwtSecret: '{"key", "", "jwk_url": "http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs"}'```

I have provided a fix in my fork to be able to specify jwk_url instead of key+type :
https://github.com/mstephano/platyplus/commit/f9c5f60e33d0ad351c0af58788520ddd067ebcb7

doc about jwk_url: https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#configuring-jwt-mode

> (type, key) pair or jwk_url, one of them has to be present.

**Comment by plmercereau** [comment]
Hi @mstephano, and thanks for the suggestion. I just bumped the Hasura chart version to 1.1.1

**Comment by mstephano** [comment]
@plmercereau Great, thank you very much for the fix! I just tried using your public chart v.1.1.1 and it works :)
