### ISSUE TITLE
Hasura: Update Ingress apiVersion for K8s 1.22+

### ISSUE THREAD

**Issue by radicand** [platyplus/platyplus#17]
Deploying in helm yields this warning currently:

```
W1113 12:53:27.725733   44587 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

As is, the chart is not deployable on a K8s 1.22 instance.

**Comment by plmercereau** [comment]
Hi Nick, thanks for this issue.
This should be solved in the latest `1.1.2` version of the chart
