### ISSUE TITLE
changing adminsecret (hasura charts) after already deployed

### ISSUE THREAD

**Issue by gdubs** [platyplus/platyplus#3]
Hi, 
I've been looking around and cannot really find anything regarding this. If I've deployed the charts on my cluster with a hardcoded adminsecret and would like to update it, do i just update the secret and redeploy? Reason I ask is because I had an issue with the postgre dependency using a persistent volume where if I update the password it will not update unless i remove the PVC and the whole thing re deploys. With that said, will I have the same concern with the admin secret of this chart?

Thanks

**Comment by plmercereau** [comment]
Hi,
The Hasura admin secret is supposed to be updated when changing it in your `values.yaml` file and upgrading your chart.

It is therefore straightforward and not as tricky as changing the postgres password. To change postgres password is indeed complicated as it is stored inside the database, and there is no simple way to automate the change with Helm yet. If interested you can monitor [this issue](https://github.com/bitnami/charts/issues/2061) - a solution would come out of it, I will adapt the Hasura Chart accordingly.

**Comment by gdubs** [comment]
Sounds good! Thank you
